language: java
jdk: openjdk8
sudo: required
services:
- docker
addons:
  chrome: stable
  apt:
    packages:
    - httpie
    - jq
#script:
#- "./travis-ci.sh"
notifications:
  slack:
    secure: DHrFlEKjTMDKKdTb1zHkLgFJdJTIh7qIwMS6fXOS3oG4JDbiYmXu6PUg7ZBRXkpsrSfJ2PdyraZ4zElrVa+85W2b3ireF0ro1NhvsdB9SJZC193MnlK5BM740tH3antCpr7ie/WtELUe9+/v4Xz3ntYgoHVx+93jv+H6/kgf3+s=
deploy:
  provider: releases
  api_key:
    secure: SPUcOtTQhyMRM2UAVp505SoIsE+wEO7ZG8Zn7S9lgv7iJq2r1Rh/Sp6RavEtPAxyeHNbAYo3J5Y2BGQ78vhD28TNLMWX2bM4ptZfVLtGwj5wGuRx+sVCgdY+CbMAtzfdvn0jy2LaXw8Via8WUfTUBgxIQWREMXpoxFhqSngfv/M=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-rally-plugin
env:
  global:
  - secure: Asv1D6XwN3F0Gww5GHOgX3uQ7vTbEPECJ4bh2xSgVG+BzXt0VG0dKSmrqHafB6jdJ1BzOSmXaPnulhSoYPR71hJdMsY2gQXYiEOe0TEUXaCEgM+++QyV4f4oR7tPZdBgra6znc1Q5GXpOMlBT9ACaAlF5syWsYR3KqNqUjhsQyQ=
  - secure: dwPcRgiBS0gTZ6o0pC3gcMzSyOdeewhrb9qH7Qo3jZVdjoV1FKwavl2JAof/OH7RdKWMxAblYKj1bD9L/7MAwzYMB0wy1+xSShJ5R6nLlQ8NMUFMyHARtJZs50UpnTxdtY+ZnDXMWqCjSYOxuWbacZhKGRiHPm8zcblfiPjCUJg=
